version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - my-cache
      - checkout
      - run: yarn install
      - save_cache:
          key: my-cache
          paths:
            - ~/node_modules
      - run: yarn test
  dark-deploy:
    requires:
      - build
    filters:
      branches:
        only: master
  hold:
    type: approval
    requires:
      - dark-deploy
    filters:
      branches:
        only: master
  deploy:
    requires:
      - hold
    machine:
        enabled: true
    working_directory: ~/repo
    environment:
      NODE_ENV: "production"
    filers:
      branches:
        only: master
    steps:
      - checkout
      - run:
          name: Install Hyper.sh CLI
          command: wget https://hyper-install.s3.amazonaws.com/hyper-linux-x86_64.tar.gz && tar xzf hyper-linux-x86_64.tar.gz && ./hyper --help
      - run:
          name: Deploy Master to Hyper.sh
          command: yarn deploy
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
