defaults: &defaults
  docker:
    - image: circleci/node:10.11
  working_directory: ~/tmp
  environment:
    NODE_ENV: "production"
  filters:
    branches:
      only: master

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - my-cache
      - checkout
      - run: yarn install
      - save_cache:
          key: my-cache
          paths:
            - ~/node_modules
      - run: yarn test
      - run: yarn build
      - persist_to_workspace:
          root: workspace
          paths:
            - build
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          keys:
            - hyper_cache
      - checkout
      - run:
          name: Install Hyper.sh CLI
          command: wget https://hyper-install.s3.amazonaws.com/hyper-linux-x86_64.tar.gz && tar xzf hyper-linux-x86_64.tar.gz && ./hyper --help
      - save_cache:
          key: hyper_cache
          paths:
            - ./hyper
      - run:
          name: Configure Hyper.sh
          command: ./hyper config --secretkey $HYPER_SECRET_KEY --accesskey $HYPER_ACCESS_KEY --default-region us-west-1
      - run:
          name: Deploy Master to Hyper.sh
          command: yarn deploy
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
