version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - my-cache
      - checkout
      - run: yarn install
      - save_cache:
          key: my-cache
          paths:
            - ~/node_modules
      - run: yarn test
  deploy:
    requires:
      - build
    docker:
      - image: circleci/node:10.11
    working_directory: ~/repo
    environment:
      NODE_ENV: "production"
    filers:
      branches:
        only: master
    steps:
      - run:
          name: Install Hyper.sh CLI
          command: wget https://hyper-install.s3.amazonaws.com/hyper-linux-x86_64.tar.gz && tar xzf hyper-linux-x86_64.tar.gz && ./hyper --help
      - run:
          name: Configure Hyper.sh
          command: ./hyper config --secretkey $HYPER_SECRET_KEY --accesskey $HYPER_ACCESS_KEY --default-region us-west-1
      - run:
          name: Deploy Master to Hyper.sh
          command: yarn deploy
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy
